#ifndef TIDECLOAK_H
#define TIDECLOAK_H

/* Warning: this file is autogenerated by cbindgen. Do not modify. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Result code for FFI functions
 */
typedef enum TcResultCode {
  Ok = 0,
  ErrConfig = 1,
  ErrNetwork = 2,
  ErrAuth = 3,
  ErrToken = 4,
  ErrNullPtr = 5,
  ErrInternal = 6,
} TcResultCode;

/**
 * Opaque handle to a TideCloak SDK instance
 */
typedef struct TideCloakInstance TideCloakInstance;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Initialize a TideCloak instance from a config file.
 *
 * Returns a pointer to the instance, or null on failure.
 * The caller must free with `tidecloak_free_instance`.
 */
struct TideCloakInstance *tidecloak_init(const char *config_path);

/**
 * Discover OIDC endpoints. Must be called before auth operations.
 *
 * Returns TcResultCode::Ok on success.
 */
enum TcResultCode tidecloak_discover(struct TideCloakInstance *instance);

/**
 * Build the authorization URL for login.
 *
 * Returns a heap-allocated C string. Caller must free with `tidecloak_free_string`.
 * Returns null on error.
 */
char *tidecloak_build_auth_url(struct TideCloakInstance *instance, const char *redirect_uri);

/**
 * Exchange an authorization code for tokens.
 *
 * Returns TcResultCode::Ok on success.
 */
enum TcResultCode tidecloak_exchange_code(struct TideCloakInstance *instance,
                                          const char *code,
                                          const char *redirect_uri);

/**
 * Refresh the current tokens.
 *
 * Returns TcResultCode::Ok on success.
 */
enum TcResultCode tidecloak_refresh(struct TideCloakInstance *instance);

/**
 * Get the current access token.
 *
 * Returns a heap-allocated C string. Caller must free with `tidecloak_free_string`.
 * Returns null if no token is available.
 */
char *tidecloak_get_access_token(struct TideCloakInstance *instance);

/**
 * Check if the access token is expired.
 */
bool tidecloak_is_token_expired(const struct TideCloakInstance *instance);

/**
 * Get user info as a JSON string.
 *
 * Returns a heap-allocated C string. Caller must free with `tidecloak_free_string`.
 * Returns null on error.
 */
char *tidecloak_get_user_info_json(const struct TideCloakInstance *instance);

/**
 * Build the logout URL.
 *
 * Returns a heap-allocated C string. Caller must free with `tidecloak_free_string`.
 * Returns null on error.
 */
char *tidecloak_logout_url(struct TideCloakInstance *instance, const char *redirect_uri);

/**
 * Get the current tokens as a JSON string (for persistence).
 *
 * Returns a heap-allocated C string. Caller must free with `tidecloak_free_string`.
 * Returns null if no tokens available.
 */
char *tidecloak_get_tokens_json(const struct TideCloakInstance *instance);

/**
 * Restore tokens from a JSON string (for persistence).
 *
 * Returns TcResultCode::Ok on success.
 */
enum TcResultCode tidecloak_set_tokens_json(struct TideCloakInstance *instance, const char *json);

/**
 * Clear all tokens (logout).
 */
void tidecloak_clear_tokens(struct TideCloakInstance *instance);

/**
 * Check if user has a realm role.
 */
bool tidecloak_has_realm_role(const struct TideCloakInstance *instance, const char *role);

/**
 * Get seconds until token expires.
 */
int64_t tidecloak_token_expires_in(const struct TideCloakInstance *instance);

/**
 * Free a string allocated by this library.
 */
void tidecloak_free_string(char *ptr);

/**
 * Free a TideCloak instance.
 */
void tidecloak_free_instance(struct TideCloakInstance *ptr);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* TIDECLOAK_H */
